version: '3.8'

services:
  postgres_db:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ildar
      POSTGRES_DB: stock_db
  eureka:
    container_name: eureka
    image: eureka
    build: ./eureka-server-app/
    ports:
      - "8761:8761"
  mongo_db:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: stock_app
      MONGO_INITDB_ROOT_PASSWORD: stock
      MONGO_INITDB_DATABASE: stock_db
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  stock-assistant-portfolio-service:
    container_name: portfolio-service
    image: stock-assistant-portfolio-service
    build: ./stock-assistant-portfolio-service/
    ports:
      - "8081:8081"
    depends_on:
      - postgres_db
      - eureka
    environment:
      EUREKA_HOST: eureka
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ildar
  stock-assistant-service:
    container_name: assistant-service
    image: stock-assistant-service
    build: ./stock-assistant-service/
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - mongo_db
    environment:
      EUREKA_HOST: eureka
      MONGODB_HOST: mongo_db
      MONGODB_PORT: 27017
      MONGODB_USERNAME: stock_app_user
      MONGODB_PASSWORD: stock
      MONGODB_DATABASE: stock_db